version: '3'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres
    ports:
      - 35432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tenhou
volumes:
  db-store:
